# -*- coding: utf-8 -*-
"""HumanGaitRecognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jY5hV8m-M2vm5Eli8iU7d3rcEy1WuAJi
"""

#Human Gait Recognition System using Data Analytics & Visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
# Sample gait dataset
data = {
    'step_length': [50,55,60,62,65,70,72,75,80,85],
    'stride_width': [20,21,22,23,24,25,26,27,28,29],
    'walking_speed': [3,3.2,3.5,3.8,4,4.2,4.5,4.8,5,5.2],
    'body_angle': [10,11,12,13,14,15,16,17,18,19],
    'person_id': [0,0,0,0,1,1,1,1,2,2]
}
df = pd.DataFrame(data)
print(df)
# Dataset information
print(df.info())
# Statistical summary
print(df.describe())
#Histogram
plt.hist(df['walking_speed'], bins=5, color='blue')
plt.title("Walking Speed Distribution")
plt.xlabel("Walking Speed")
plt.ylabel("Frequency")
plt.show()
#Scatter Plot
plt.scatter(df['step_length'], df['walking_speed'], color='red')
plt.title("Step Length vs Walking Speed")
plt.xlabel("Step Length")
plt.ylabel("Walking Speed")
plt.show()
#Heatmap
sns.heatmap(df.corr(), annot=True)
plt.title("Feature Correlation Heatmap")
plt.show()